import fs from 'fs';
import { ScrapeResult } from './scraper';

/**
 * Generates SQL INSERT statements from scraped data
 * @param data - Array of scraped data objects
 * @param tableName - Name of the SQL table to insert into
 * @param filename - Output filename for the SQL file
 */
export function exportToSql(data: ScrapeResult[], tableName: string, filename: string): void {
  if (data.length === 0) {
    console.log('No data to export');
    return;
  }

  // Get column names from the first data object
  const columns = data.length > 0 ? Object.keys(data[0]) : [];
  
  // Generate the SQL file content
  let sqlContent = `-- SQL export generated by Web Scraper CLI\n\n`;
  sqlContent += `-- Create table statement (example)\n`;
  sqlContent += `CREATE TABLE IF NOT EXISTS ${tableName} (\n`;
  
  // Add columns to CREATE TABLE statement
  const columnDefinitions = columns.map(col => `  ${col.replace(/[^a-zA-Z0-9_]/g, '_')} TEXT`).join(',\n');
  sqlContent += columnDefinitions;
  sqlContent += '\n);\n\n';
  
  // Generate INSERT statements
  sqlContent += "-- Insert statements\n";
  data.forEach(item => {
    const values = columns.map(col => {
      // Escape single quotes in string values and wrap in quotes
      const value = item[col] !== undefined && item[col] !== null 
        ? String(item[col]).replace(/'/g, "''") 
        : 'NULL';
      return `'${value}'`;
    }).join(', ');
    
    sqlContent += `INSERT INTO ${tableName} (${columns.map(col => col.replace(/[^a-zA-Z0-9_]/g, '_')).join(', ')}) VALUES (${values});\n`;
  });

  // Write the SQL content to file
  fs.writeFileSync(filename, sqlContent);
  console.log(`Data exported to ${filename}`);
}